### ISSUE TITLE
Learning Placeholders for Open-Set Recognition

### ISSUE THREAD

**Issue by li-shipeng** [zhoudw-zdw/Awesome-open-world-learning#1]
It is a great job about your paper _Learning Placeholders for Open-Set Recognition_ in CVPR2021. When the code is to be accessible in GitHub? Thank you for your contribution to open-set recognition.

**Comment by li-shipeng** [comment]
Hi Dawei Zhou,

If the code would not be public as soon, could you please introduce the procedure of calibration about bias in more detail? I am confused about how to obtain the best bias? 
1)Does each placeholder classifier is equipped with a different bias? 
2)What are the relationships between the magnitude logit difference with bias? 
3)How can we set the best bias achieving 95% accuracy, by SGD or others?

Thank U again for your efforts in the society of open-set recognition.

Shipeng Li

**Comment by zhoudw-zdw** [comment]
Hi, code is available at: https://github.com/zhoudw-zdw/CVPR21-Proser
